version: '3.1'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5555:5432"

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
