module.exports = [
  { name: 'Air Intake' },
  { name: 'Audio/Video' },
  { name: 'Brakes' },
  { name: 'Cooling' },
  { name: 'Drivetrain' },
  { name: 'Electrical' },
  { name: 'Engine' },
  { name: 'Exhaust' },
  { name: 'Exterior' },
  { name: 'Fluids' },
  { name: 'Fuel System' },
  { name: 'HVAC' },
  { name: 'Ignition' },
  { name: 'Interior' },
  { name: 'Lighting' },
  { name: 'Safety' },
  { name: 'Suspension/Steering' },
  { name: 'Wheels & Tires' },
  { name: 'Tools' },
];
