module.exports = {
  user: 'user',
  build_type: 'build_type',
  ownership_status: 'ownership_status',
  part_category: 'part_category',
  part_status: 'part_status',
  record_type: 'record_type',
  image_type: 'image_type',
  make: 'make',
  country: 'country',
  state: 'state',
  address: 'address',
  company: 'company',
  model: 'model',
  submodel: 'submodel',
  model_year: 'model_year',
  vehicle: 'vehicle',
  vehicle_info: 'vehicle_info',
  vehicle_spec: 'vehicle_spec',
  vehicle_image: 'vehicle_image',
  part: 'part',
  part_info: 'part_info',
  part_image: 'part_image',
  record: 'record',
  record_info: 'record_info',
  record_image: 'record_image',
};
